# These are supported funding model platforms

github: panasabena
# Open Collective: opencollective
# Ko-fi: kofi
# Tidelift: tidelift
# Community Bridge: community_bridge
# Liberapay: liberapay
# IssueHunt: issuehunt
# Otechie: otechie
# Custom: custom
